version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: sodamsodam-db
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: sodamsodam
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - my-network

  redis:
    image: redis:7-alpine
    container_name: sodamsodam-redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis-data:/data
    networks:
      - my-network

  spring:
    build: .
    container_name: sodamsodam-app
    depends_on:
      - mysql
      - redis
    environment:
      SPRING_DATASOURCE_URL: ${DB_URL}
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
      KAKAO_CLIENT_ID: ${KAKAO_CLIENT_ID}
      KAKAO_REDIRECT_URI: ${KAKAO_REDIRECT_URI}
      MY_AWS_SECRET_KEY: ${MY_AWS_SECRET_KEY}
      MY_AWS_ACCESS_KEY: ${MY_AWS_ACCESS_KEY}
    ports:
      - "8080:8080"
    networks:
      - my-network

volumes:
  mysql-data:
  redis-data:

networks:
  my-network: